name:                adventofcode
version:             0.1.0.0
github:              "githubuser/adventofcode"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- containers
- split
- vector
- lens
- mtl
- repa
- vector
- generic-lens
- deepseq
- criterion-measurement

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-ignore-asserts 

default-extensions:
- OverloadedStrings
- ImportQualifiedPost
- TemplateHaskell
- DisambiguateRecordFields
- DuplicateRecordFields
- OverloadedLabels
- DeriveGeneric
- GADTs
- RankNTypes
- StandaloneDeriving
- NoMonomorphismRestriction
- TypeFamilies
- FlexibleContexts
- DataKinds
- FlexibleInstances
- FunctionalDependencies
- UndecidableInstances
- PartialTypeSignatures
- RecordWildCards
- DeriveDataTypeable
- ScopedTypeVariables
- GeneralizedNewtypeDeriving
- TypeOperators
- ViewPatterns
- BangPatterns
- DeriveFunctor
- InstanceSigs
- LiberalTypeSynonyms
- ImpredicativeTypes
- DefaultSignatures

executables:
  dayone-exe:
    main:                Main.hs
    source-dirs:         day_one
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  daytwo-exe:
    main:               Main.hs
    source-dirs:        day_two
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  daythree-exe:
    main:               Main.hs
    source-dirs:        day_three
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  dayfour-exe:
    main:               Main.hs
    source-dirs:        day_four
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  dayfive-exe:
    main:               Main.hs
    source-dirs:        day_five
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  day6:
    main:               Main.hs
    source-dirs:        day6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2021-day-25:
    main:               Main.hs
    source-dirs:        aoc2021_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2021-day-24:
    main:               Main.hs
    source-dirs:        aoc2021_day_24
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2020-day-25:
    main:               Main.hs
    source-dirs:        aoc2020_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2018-day-25:
    main:               Main.hs
    source-dirs:        aoc2018_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2017-day-25:
    main:               Main.hs
    source-dirs:        aoc2017_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode

library:
  source-dirs: lib
