name:                adventofcode
version:             0.1.0.0
github:              "githubuser/adventofcode"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- containers
- split
- vector
- lens
- mtl
- repa
- vector
- generic-lens
- deepseq
- criterion-measurement
- accelerate
- accelerate-llvm-ptx
- accelerate-llvm-native
- lens-accelerate
- pretty-simple
- cmdargs
- hmatrix
- fgl
- parallel
- monad-coroutine

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-ignore-asserts 

default-extensions:
- OverloadedStrings
- ImportQualifiedPost
- TemplateHaskell
- DisambiguateRecordFields
- DuplicateRecordFields
- OverloadedLabels
- DeriveGeneric
- GADTs
- RankNTypes
- StandaloneDeriving
- NoMonomorphismRestriction
- TypeFamilies
- FlexibleContexts
- DataKinds
- FlexibleInstances
- FunctionalDependencies
- UndecidableInstances
- PartialTypeSignatures
- RecordWildCards
- DeriveDataTypeable
- ScopedTypeVariables
- GeneralizedNewtypeDeriving
- TypeOperators
- ViewPatterns
- BangPatterns
- DeriveFunctor
- InstanceSigs
- LiberalTypeSynonyms
- ImpredicativeTypes
- DefaultSignatures

executables:
  aoc2022-day-01:
    main:                Main.hs
    source-dirs:         aoc2022_day_01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-02:
    main:               Main.hs
    source-dirs:        aoc2022_day_02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-03:
    main:               Main.hs
    source-dirs:        aoc2022_day_03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-04:
    main:               Main.hs
    source-dirs:        aoc2022_day_04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-05:
    main:               Main.hs
    source-dirs:        aoc2022_day_05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-06:
    main:               Main.hs
    source-dirs:        aoc2022_day_06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-07:
    main:               Main.hs
    source-dirs:        aoc2022_day_07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-08:
    main:               Main.hs
    source-dirs:        aoc2022_day_08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-09:
    main:               Main.hs
    source-dirs:        aoc2022_day_09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-10:
    main:               Main.hs
    source-dirs:        aoc2022_day_10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-11:
    main:               Main.hs
    source-dirs:        aoc2022_day_11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-12:
    main:               Main.hs
    source-dirs:        aoc2022_day_12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-13:
    main:               Main.hs
    source-dirs:        aoc2022_day_13
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-14:
    main:               Main.hs
    source-dirs:        aoc2022_day_14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-15:
    main:               Main.hs
    source-dirs:        aoc2022_day_15
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2022-day-16:
    main:               Main.hs
    source-dirs:        aoc2022_day_16
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - adventofcode
  aoc2022-day-17:
    main:               Main.hs
    source-dirs:        aoc2022_day_17
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2021-day-25:
    main:               Main.hs
    source-dirs:        aoc2021_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2021-day-24:
    main:               Main.hs
    source-dirs:        aoc2021_day_24
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-n2M
    - -with-rtsopts=-A64M
    dependencies:
    - adventofcode
  aoc2020-day-25:
    main:               Main.hs
    source-dirs:        aoc2020_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2018-day-25:
    main:               Main.hs
    source-dirs:        aoc2018_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
  aoc2017-day-25:
    main:               Main.hs
    source-dirs:        aoc2017_day_25
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode

library:
  source-dirs: lib
